name: Build and Publish NuGet

on:
  push:
    branches:
      - main
    tags:
      - 'Release-*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true
  
    - name: Unshallow repository
      run: git fetch --prune --unshallow

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Add GitHub Packages NuGet source
      shell: pwsh
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/eduarddanziger/index.json `
          --name github `
          --username eduarddanziger `
          --password ${{ secrets.NUGET_AUTH_TOKEN }} `
          --store-password-in-clear-text

    - name: Restore NuGet packages
      run: nuget restore CommonLibsCpp.sln

    - name: Integrate vcpkg with MSBuild
      run: vcpkg integrate install

    - name: Build with MSBuild
      run: msbuild /t:ValidateSolution /p:Configuration=Release

    - name: Push NuGet to GitHub Packages
      env:
        NUGET_SOURCE: https://nuget.pkg.github.com/eduarddanziger/index.json
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        Get-ChildItem artifacts\*.nupkg | ForEach-Object { 
          dotnet nuget push $_.FullName `
              --source "$env:NUGET_SOURCE" `
              --api-key "$env:GITHUB_TOKEN"
        }
